###Purpose: Aggregate all significant results from each of 6 intestinal sites into one vector; then query this vector against "all results" output from each of six sites 
library(data.table)
library(janitor)
library(stringi)
library(stringr)
library(funrar)
library(lessR)
library(ggplot2)
library(tidyr)
library(gplots)
library(dplyr)
library(here)

here::i_am("MouseBiogeography-RProj/CS_Facility_Metabolic_Map_Prep.R")
annotation <- read.csv("GMM_Module_Key.csv", header=TRUE)

### for SI vs Colon ---
input<-read.table("Donors-Analysis/differential_GMM_site/GMM-ColonRef-CLR-Lum-ComBat-SeqRunSexSite_General-1-MsID-DonorID/significant_results.tsv", header=TRUE)
data<-input %>% filter(metadata=="Site_General" & qval<0.05)
data<- (merge(data, annotation, by = 'feature'))
unique(data$Map)
data <- data %>% select(c(feature, coef,Map,Map2_ammonia,Map3_carbon_dioxide))
polysaccharides <- data %>% filter(Map=="polysaccharides")
mono <- data %>% filter(Map=="monosaccharides")
di <- data %>% filter(Map=="disaccharides")
sug_acid<- data %>% filter(Map=="sugar acid")
sug_alc<- data %>% filter(Map=="sugar alcohol")
protein<- data %>% filter(Map=="proteolytic fermentation")
fat<- data %>% filter(Map=="lipolytic fermentation")
muc<- data %>% filter(Map=="mucin degradation")
nrg<- data %>% filter(Map=="energy storage")
etoh<- data %>% filter(Map=="ethanol")
cent<- data %>% filter(Map=="central metabolism")
acetate<- data %>% filter(Map=="acetate")
butyrate<- data %>% filter(Map=="butyrate")
propionate<- data %>% filter(Map=="propionate")
h2<- data %>% filter(Map=="hydrogen")
no2<- data %>% filter(Map=="nitrate reduction")
cf<- data %>% filter(Map=="cross-feeding")
aceto<- data %>% filter(Map=="acetogenesis")
nh3<- data %>% filter(Map2_ammonia=="ammonia")
co2<- data %>% filter(Map3_carbon_dioxide=="carbon dioxide")

input<-read.table("Donors-Analysis/differential_GMM_site/GMM-ColonRef-CLR-Muc-ComBat-SeqRunSexSite_General-1-MsID-DonorID/significant_results.tsv", header=TRUE)
data<-input %>% filter(metadata=="Site_General" & qval<0.05)
data<- (merge(data, annotation, by = 'feature'))
unique(data$Map)
data <- data %>% select(c(feature, coef,Map,Map2_ammonia,Map3_carbon_dioxide))
polysaccharides <- data %>% filter(Map=="polysaccharides")
di <- data %>% filter(Map=="disaccharides")
mono <- data %>% filter(Map=="monosaccharides")
muc<- data %>% filter(Map=="mucin degradation")
sug_acid<- data %>% filter(Map=="sugar acid")
protein<- data %>% filter(Map=="proteolytic fermentation")
fat<- data %>% filter(Map=="lipolytic fermentation")
cent<- data %>% filter(Map=="central metabolism")
h2<- data %>% filter(Map=="hydrogen")
cf<- data %>% filter(Map=="cross-feeding")
co2<- data %>% filter(Map3_carbon_dioxide=="carbon dioxide")
methane<- data %>% filter(Map=="methane")
propionate<- data %>% filter(Map=="propionate")
butyrate<- data %>% filter(Map=="butyrate")
etoh<- data %>% filter(Map=="ethanol")
aceto<- data %>% filter(Map=="acetogenesis")
no2<- data %>% filter(Map=="nitrate reduction")

nrg<- data %>% filter(Map=="energy storage")
acetate<- data %>% filter(Map=="acetate")
nh3<- data %>% filter(Map2_ammonia=="ammonia")

### for Muc vs Lum ---
input<-read.table("Donors-Analysis/differential_GMM_type/GMM-LumRef-CLR-Colon-ComBat-SeqRunSexSiteType-1-MsID/significant_results.tsv",header = TRUE)
data<-filter(input, metadata=="Type" & qval<0.05)
data<- (merge(data, annotation, by = 'feature'))
unique(data$Map)
data <- data %>% select(c(feature, coef,Map,Map2_ammonia,Map3_carbon_dioxide))
polysaccharides <- data %>% filter(Map=="polysaccharides")
di <- data %>% filter(Map=="disaccharides")
mono <- data %>% filter(Map=="monosaccharides")
muc<- data %>% filter(Map=="mucin degradation")
sug_acid<- data %>% filter(Map=="sugar acid")
protein<- data %>% filter(Map=="proteolytic fermentation")
fat<- data %>% filter(Map=="lipolytic fermentation")
cent<- data %>% filter(Map=="central metabolism")
h2<- data %>% filter(Map=="hydrogen")
cf<- data %>% filter(Map=="cross-feeding")
co2<- data %>% filter(Map3_carbon_dioxide=="carbon dioxide")
methane<- data %>% filter(Map=="methane")
propionate<- data %>% filter(Map=="propionate")
butyrate<- data %>% filter(Map=="butyrate")
etoh<- data %>% filter(Map=="ethanol")
aceto<- data %>% filter(Map=="acetogenesis")
no2<- data %>% filter(Map=="nitrate reduction")
sulf<- data %>% filter(Map=="sulfate reduction")

nrg<- data %>% filter(Map=="energy storage")
acetate<- data %>% filter(Map=="acetate")
nh3<- data %>% filter(Map2_ammonia=="ammonia")


input<-read.table("Donors-Analysis/differential_GMM_type/GMM-LumRef-CLR-SI-ComBat-SeqRunSexSiteType-1-MsID/significant_results.tsv",header = TRUE)
data<-filter(input, metadata=="Type" & qval<0.05)
data<- (merge(data, annotation, by = 'feature'))
unique(data$Map)
data <- data %>% select(c(feature, coef,Map,Map2_ammonia,Map3_carbon_dioxide))
polysaccharides <- data %>% filter(Map=="polysaccharides")
di <- data %>% filter(Map=="disaccharides")
mono <- data %>% filter(Map=="monosaccharides")
muc<- data %>% filter(Map=="mucin degradation")
sug_acid<- data %>% filter(Map=="sugar acid")
protein<- data %>% filter(Map=="proteolytic fermentation")
fat<- data %>% filter(Map=="lipolytic fermentation")
cent<- data %>% filter(Map=="central metabolism")
h2<- data %>% filter(Map=="hydrogen")
cf<- data %>% filter(Map=="cross-feeding")
co2<- data %>% filter(Map3_carbon_dioxide=="carbon dioxide")
methane<- data %>% filter(Map=="methane")
propionate<- data %>% filter(Map=="propionate")
butyrate<- data %>% filter(Map=="butyrate")
etoh<- data %>% filter(Map=="ethanol")
aceto<- data %>% filter(Map=="acetogenesis")
no2<- data %>% filter(Map=="nitrate reduction")
sulf<- data %>% filter(Map=="sulfate reduction")

nrg<- data %>% filter(Map=="energy storage")
acetate<- data %>% filter(Map=="acetate")
nh3<- data %>% filter(Map2_ammonia=="ammonia")

