###Purpose: Aggregate all significant results from each of 6 intestinal sites into one vector; then query this vector against "all results" output from each of six sites 
library(data.table)
library(janitor)
library(stringi)
library(stringr)
library(funrar)
library(lessR)
library(ggplot2)
library(tidyr)
library(gplots)
library(dplyr)

here::i_am("MouseBiogeography-RProj/CS_Facility_Metabolic_Map_Prep.R")
annotation <- read.csv("GMM_Module_Key.csv", header=TRUE)

### for SI vs Colon ---
input<-read.table("Shotgun/UCLA_O_SPF/GMM-DCvsJej-CLR-UCLA-ComBat-SeqRunLineSexSite-1-MsID/significant_results.tsv", header=TRUE)
data<-input %>% filter(metadata=="Site" & qval<0.05)
data<- (merge(data, annotation, by = 'feature'))
unique(data$Map)
data <- data %>% select(c(feature, coef,Map,Map2_ammonia,Map3_carbon_dioxide))
mono <- data %>% filter(Map=="monosaccharides")
di <- data %>% filter(Map=="disaccharides")
protein<- data %>% filter(Map=="proteolytic fermentation")
fat<- data %>% filter(Map=="lipolytic fermentation")
cent<- data %>% filter(Map=="central metabolism")
butyrate<- data %>% filter(Map=="butyrate")
cf<- data %>% filter(Map=="cross-feeding")
nh3<- data %>% filter(Map2_ammonia=="ammonia")
co2<- data %>% filter(Map3_carbon_dioxide=="carbon dioxide")

input<-read.table("Shotgun/CS_SPF/GMM-DCvsJej-CLR-CS-ComBat-SeqRunSexSite-1-MsID/significant_results.tsv", header=TRUE)
data<-input %>% filter(metadata=="Site" & qval<0.05)
data<- (merge(data, annotation, by = 'feature'))
unique(data$Map)
data <- data %>% select(c(feature, coef,Map,Map2_ammonia,Map3_carbon_dioxide))
fat<- data %>% filter(Map=="lipolytic fermentation")
cent<- data %>% filter(Map=="central metabolism")
cf<- data %>% filter(Map=="cross-feeding")
nh3<- data %>% filter(Map2_ammonia=="ammonia")
co2<- data %>% filter(Map3_carbon_dioxide=="carbon dioxide")

input<-read.table("Shotgun/SPF_Gavage/GMM-DCvsJej-CLR-SPF-ComBat-SeqRunSexSite-1-MsID/significant_results.tsv", header=TRUE)
data<-input %>% filter(metadata=="Site" & qval<0.05)
data<- (merge(data, annotation, by = 'feature'))
unique(data$Map)
data <- data %>% select(c(feature, coef,Map,Map2_ammonia,Map3_carbon_dioxide))
protein<- data %>% filter(Map=="proteolytic fermentation")
fat<- data %>% filter(Map=="lipolytic fermentation")
nh3<- data %>% filter(Map2_ammonia=="ammonia")
co2<- data %>% filter(Map3_carbon_dioxide=="carbon dioxide")


input<-read.table("Shotgun/HUM_Gavage/GMM-DCvsJej-CLR-HUM-ComBat-SeqRunSexSite-1-MsID/significant_results.tsv", header=TRUE)
data<-input %>% filter(metadata=="Site" & qval<0.05)
data<- (merge(data, annotation, by = 'feature'))
unique(data$Map)
data <- data %>% select(c(feature, coef,Map,Map2_ammonia,Map3_carbon_dioxide))
protein<- data %>% filter(Map=="proteolytic fermentation")
mono <- data %>% filter(Map=="monosaccharides")
etoh <- data %>% filter(Map=="ethanol")

nh3<- data %>% filter(Map2_ammonia=="ammonia")
co2<- data %>% filter(Map3_carbon_dioxide=="carbon dioxide")
